In [1]:
import numpy as np
import pandas as pd
import astropy.units as u
from GalaxyMass import ComponentMass

In [13]:
galaxies = ['MW', 'M31', 'M33'] # set up the galaxy names to iterate over
components = ['Halo', 'Disk', 'Bulge'] # set up the component to iterate over
masses = np.zeros((4,4))*u.Msun # make array to store the masses in
# columns are: halo, disk, bulge, total
# rows are: MW, M31, M33, Local Group
barfracs = np.zeros((4,1)) # make array to store the baryon fractions in
# same galaxy order as above

In [14]:
# calculate masses and baryon fractions for all 3 galaxies
for i in range(0,3): # iterate over the galaxies

    galaxy = galaxies[i] # this is the galaxy we're working with
    # make the path to the file with the galaxy data we want 
    fpath = '/home/hal9k/HAL-ASTR400B/Homeworks/Homework3/'+galaxy+'_000.txt'

    for j in range(0,3): # iterate over the components of this galaxy

        component = components[j] # this is the component we're working with
        # calculate the component mass and assign it to the correct spot in the array
        masses[i,j] = ComponentMass(fpath, component)

    # calculate the total mass of this galaxy
    mtot = np.sum(masses[i,:3]) # sum component masses
    masses[i,3] = mtot # assign it to the correct spot in the array

    # calculate the baryon fraction of this galaxy
    barfrac = (masses[i,1]+masses[i,2])/masses[i,3] # stellar mass (disk + bulge) / total mass
    # assign it to the correct spot after rounding to 3 decimal points
    barfracs[i] = np.around(barfrac, 3)


In [15]:
# calculate masses and baryon fraction for local group
for i in range(0,4): # iterate over the mass types (including total)
    mass_lg = np.sum(masses[:3,i]) # sum the masses of the 3 galaxies
    masses[3,i] = mass_lg # assign it to the correct spot in the array

barfrac_lg = (masses[3,1]+masses[3,2])/masses[3,3] # calculate the baryon fraction
# assign it to the correct spot after rounding to 3 decimal points
barfracs[3] = np.around(barfrac_lg, 3)

In [16]:
# to check if everything makes sense - it does!
print(masses)
print(barfracs)

[[1.975 0.075 0.01  2.06 ]
 [1.921 0.12  0.019 2.06 ]
 [0.187 0.009 0.    0.196]
 [4.083 0.204 0.029 4.316]] solMass
[[0.041]
 [0.067]
 [0.046]
 [0.054]]


In [19]:
# put everything into a dictionary first
masses_dict = {'Galaxy Name':['Milky Way', 'M31', 'M33', 'Local Group'],
               'Halo Mass (10^12 M_sun)':masses[:,0].value,
               'Disk Mass (10^12 M_sun)':masses[:,1].value,
               'Bulge Mass (10^12 M_sun)':masses[:,2].value,
               'Total Mass (10^12 M_sun)':masses[:,3].value,
               'f_bar':barfracs.flatten()}
# and then turn it into a pandas dataframe to make it easier to read
masses_df = pd.DataFrame(masses_dict)

In [21]:
# look at the pretty dataframe as I put all this into a LaTeX table
masses_df

Galaxy Name  Halo Mass (10^12 M_sun)  Disk Mass (10^12 M_sun)  \
0    Milky Way                    1.975                    0.075   
1          M31                    1.921                    0.120   
2          M33                    0.187                    0.009   
3  Local Group                    4.083                    0.204   

   Bulge Mass (10^12 M_sun)  Total Mass (10^12 M_sun)  f_bar  
0                     0.010                     2.060  0.041  
1                     0.019                     2.060  0.067  
2                     0.000                     0.196  0.046  
3                     0.029                     4.316  0.054